spring:
  jpa:
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql=true: true
  datasource:
    url: jdbc:sqlite:src/main/resources/student.db
    driver-class-name: org.sqlite.JDBC