# configurazione del server
spring:
  profiles:
    #active: sqlite|postgres|test
    #active: sqlite
    active: postgres

server:
  port: 8092
  servlet:
    contextPath: /studentCourseBook


# impostazioni per hibernate
hibernate:
  hbm2ddl:
    auto: none
  show-sql: true